<?php
/**
 * Implements hook_install().
 * Custom Module to log all the changes made in the website.
 *
 */
function drupal_jenkins_dev_deploy_install() {
  if(function_exists('drupal_jenkins_dev_deploy_update_17')) {
      drupal_jenkins_dev_deploy_update_17();
  }
}

/**
 * @ticketid: Enable javascript aggregation
 */
function drupal_jenkins_dev_deploy_update_1() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_2() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_3() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_4() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_5() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_6() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_7() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_8() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_9() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_10() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_11() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_12() {
  module_disable(array('toolbar'));
}

function drupal_jenkins_dev_deploy_update_13() {
  module_enable(array('toolbar'));
}

function drupal_jenkins_dev_deploy_update_14() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_15() {
  module_enable(array('features', 'test_content_type'));
}
function drupal_jenkins_dev_deploy_update_16() {
  module_enable(array('features', 'test_content_type'));
}
function drupal_jenkins_dev_deploy_update_17() {
  module_disable(array('deploy_development_process'));
}

