<?php
/**
 * Implements hook_install().
 *
 */
function drupal_jenkins_dev_deploy_install() {
  if(function_exists('drupal_jenkins_dev_deploy_update_5')) {
      drupal_jenkins_dev_deploy_update_5();
  }
}

/**
 * @ticketid: Enable javascript aggregation
 */
function drupal_jenkins_dev_deploy_update_1() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_2() {
  module_enable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_3() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_4() {
  module_disable(array('toolbar'));
}
function drupal_jenkins_dev_deploy_update_5() {
  module_enable(array('toolbar'));
}

